version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Default linters
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced Go linter (includes gosimple)
    - unused        # Check for unused code

    # Additional recommended linters
    - misspell      # Check for misspelled English words
    - revive        # Fast, configurable, extensible linter
    - gosec         # Security-focused linter
    - unconvert     # Remove unnecessary type conversions
    - unparam       # Check for unused function parameters
    - bodyclose     # Check if HTTP response bodies are closed
    - noctx         # Check for sending HTTP requests without context
    - errorlint     # Check for common mistakes with Go error wrapping

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

    govet:
      enable-all: true
      disable:
        - shadow  # Can be too strict
        - fieldalignment  # Minor optimization, not worth the complexity

    revive:
      rules:
        - name: exported
          disabled: true  # Sometimes too strict for CLI tools

    gosec:
      excludes:
        - G204  # Subprocess launched with variable - needed for git/tmux commands
        - G301  # Directory permissions 0755 are acceptable for worktree directories
        - G304  # File inclusion via variable is expected for a CLI tool
        - G306  # File permissions 0644 are acceptable for config files

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
